FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["S3DB-Individual-Project-Tony/S3DB-Individual-Project-Tony.csproj", "S3DB-Individual-Project-Tony/"]
COPY ["Core/Core.csproj", "Core/"]
COPY ["DataAccess/DataAccess.csproj", "DataAccess/"]
COPY ["CloudinaryAccess/CloudinaryAccess.csproj", "CloudinaryAccess/"]
RUN dotnet restore "S3DB-Individual-Project-Tony/S3DB-Individual-Project-Tony.csproj"
COPY . .
WORKDIR "/src/S3DB-Individual-Project-Tony"
RUN dotnet build "S3DB-Individual-Project-Tony.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "S3DB-Individual-Project-Tony.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "S3DB-Individual-Project-Tony.dll"]
