name: ASP.NET Core CI/CD 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # disable shallow clones
          
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
          
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      working-directory: S3DB-Individual-Project-Tony
      run: dotnet restore 

    - name: Build project
      run: dotnet build 

    - name: Run xUnit tests
      run: dotnet test --no-build --verbosity normal 


    - name: Run Docker
      working-directory: S3DB-Individual-Project-Tony
      run: |
        docker build -f .\Dockerfile -t shop_hop_api .
        docker run --name ShopHopAPI -it --rm -dp 8000:8080 --network=ShopHop-Network shop_hop_api
